[package]
name = "terminal_typer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
lipsum = "0.9.0"
ratatui = "0.20.1"
